### ISSUE TITLE
Instance not launching 

### ISSUE THREAD

**Issue by AMN-D** [denisapain/PrismLauncherAccountBypass#1]
![image](https://github.com/denisapain/PrismLauncherAccountBypass/assets/129135638/9608151e-cff5-4b8a-b66e-43884364a06f)

when i click on Launch ( Launching for the first time ) nothing happens

**Comment by denisapain** [comment]
This seems to be a bug with Prismlauncher, as it has happened to be before with my genuine account, first off, make a new cracked account in the accounts manager and delete the "No profile" one, and second, kill Prismlauncher with task manager and re-launch the instance.

**Comment by denisapain** [comment]
You may also try to re-download the assets. and then launch the game
![image](https://github.com/denisapain/PrismLauncherAccountBypass/assets/126583428/6386e11f-0191-4cb8-8fcc-3b2dc9ef70f7)

**Comment by AMN-D** [comment]
thanks for replying
it started downloading the files after i added and changed to a different offline user .
