### ISSUE TITLE
I was wondering is their anyway to change the skin to alex ? 

### ISSUE THREAD

**Issue by AMN-D** [denisapain/PrismLauncherAccountBypass#2]
Not an issue , i was wondering if i can get the female variant of skin .

**Comment by denisapain** [comment]
unfortunately it looks like you can choose a specific skin for a online account online, looks like it selects a random skin, you could try to use a plugin like skinsrestorer if playing on a server

you could try using a clientsided mod like this [https://www.curseforge.com/minecraft/mc-mods/offlineskins](https://www.curseforge.com/minecraft/mc-mods/offlineskins)

**Comment by denisapain** [comment]
you could also try to use ely.by [https://ely.by/load](https://ely.by/load)
(do not use TLauncher, it is a spyware, and maybe virus)
